version: 2.1
jobs:
  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: run unit tests 
          command: |
            go test
      - run:
          name: run integration tests 
          command: |
            ./integration-tests/test.sh .
workflows:
  version: 2
  build:
    jobs:
      - test
    
        
    